import type { ExtensionAPI, ToolDefinition } from '@earendil-works/pi-coding-agent';
import { registerAllTools } from '../extensions/tools/index.ts';

/**
 * Capture the tool definitions without a running agent.
 *
 * Documentation and the tool-count cap are checked against what the extension
 * actually registers, so a new tool cannot be added without the docs check
 * noticing.
 */
export interface CapturedTool {
  name: string;
  label: string;
  description: string;
  promptSnippet?: string;
  promptGuidelines?: string[];
  parameters: unknown;
  execute: ToolDefinition['execute'];
}

export function captureTools(): CapturedTool[] {
  const captured: CapturedTool[] = [];
  const pi = {
    registerTool(tool: ToolDefinition) {
      captured.push({
        name: tool.name,
        label: tool.label,
        description: tool.description,
        promptSnippet: tool.promptSnippet,
        promptGuidelines: tool.promptGuidelines,
        parameters: tool.parameters,
        execute: tool.execute,
      });
    },
  } as unknown as ExtensionAPI;
  registerAllTools(pi);
  return captured.sort((left, right) => left.name.localeCompare(right.name));
}

function schemaOf(tool: CapturedTool): string {
  return JSON.stringify(tool.parameters, null, 2);
}

export function renderToolsDoc(): string {
  const tools = captureTools();
  const lines: string[] = [
    '# Tools',
    '',
    '<!-- Generated by `npm run docs`. Do not edit by hand. -->',
    '',
    `The extension registers **${tools.length} tools**. Adding an eleventh is a`,
    'deliberate decision: a new capability is expected to extend an existing tool',
    'with a parameter unless it answers a question none of them can.',
    '',
  ];
  for (const tool of tools) {
    lines.push(`## \`${tool.name}\``, '', tool.description, '');
    lines.push(`- Label: ${tool.label}`);
    if (tool.promptSnippet) lines.push(`- Prompt snippet: ${tool.promptSnippet}`);
    lines.push('');
    if (tool.promptGuidelines?.length) {
      lines.push('Prompt guidelines:', '');
      for (const guideline of tool.promptGuidelines) lines.push(`- ${guideline}`);
      lines.push('');
    }
    lines.push('Parameters:', '', '```json', schemaOf(tool), '```', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}
